// Migrated from v1.2.0 -> v2.0.0
// Category: handlers-clean

export const main = {
    namespace: 'feiertage',
    name: 'Feiertage API',
    description: 'German public holidays API providing holiday dates for all federal states with optional state filtering',
    version: '4.0.0',
    docs: ['https://feiertage-api.de/'],
    tags: ['holidays', 'germany', 'calendar', 'cacheTtlStatic'],
    root: 'https://feiertage-api.de/api',
    tools: {
        getAllHolidays: {
            method: 'GET',
            path: '/',
            description: 'Get public holidays for all German federal states for a given year. Returns holiday name, date, and optional notes per state. The postRequest handler restructures the response into a flat array. Use state codes (BW, BY, etc.) with getStateHolidays for a single state.',
            parameters: [
                { position: { key: 'jahr', value: '{{USER_PARAM}}', location: 'query' }, z: { primitive: 'string()', options: ['default("2026")', 'optional()'] } }
            ],
            tests: [
                { _description: 'Get all holidays for 2026' }
            ],
            output: {
                mimeType: 'application/json',
                schema: {
                    type: 'object',
                    description: 'Public holidays for all 16 German federal states. Keys are state codes (BW, BY, BE, BB, HB, HH, HE, MV, NI, NW, RP, SL, SN, ST, SH, TH, NATIONAL). Each state maps holiday names to objects with datum (ISO date YYYY-MM-DD) and hinweis (optional note or caveat, empty string if none).',
                    properties: {
                        BW: { type: 'object', description: 'Baden-Wuerttemberg holidays', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string', description: 'Holiday date in YYYY-MM-DD format' }, hinweis: { type: 'string', description: 'Optional note or caveat about this holiday (empty string if none)' } } }, 'Heilige Drei Könige': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Fronleichnam: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Reformationstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Allerheiligen: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        BY: { type: 'object', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Heilige Drei Könige': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Fronleichnam: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Augsburger Friedensfest': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Mariä Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Allerheiligen: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Buß- und Bettag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        BE: { type: 'object', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Frauentag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        BB: { type: 'object', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostersonntag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstsonntag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Reformationstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        HB: { type: 'object', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Reformationstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        HH: { type: 'object', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Reformationstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        HE: { type: 'object', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Fronleichnam: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        MV: { type: 'object', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Frauentag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Reformationstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        NI: { type: 'object', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Reformationstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        NW: { type: 'object', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Fronleichnam: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Allerheiligen: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        RP: { type: 'object', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Fronleichnam: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Allerheiligen: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        SL: { type: 'object', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Fronleichnam: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Mariä Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Allerheiligen: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        SN: { type: 'object', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Fronleichnam: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Reformationstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Buß- und Bettag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        ST: { type: 'object', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Heilige Drei Könige': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Reformationstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        SH: { type: 'object', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Reformationstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        TH: { type: 'object', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Fronleichnam: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Weltkindertag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Reformationstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } },
                        NATIONAL: { type: 'object', description: 'Nationwide holidays observed in all federal states', properties: { Neujahrstag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, 'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }, '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } } } }
                    }
                }
            },
        },
        getStateHolidays: {
            method: 'GET',
            path: '/',
            description: 'Get public holidays for a specific German federal state. States: BW, BY, BE, BB, HB, HH, HE, MV, NI, NW, RP, SL, SN, ST, SH, TH. Returns a subset of getAllHolidays for one state. Use getAllHolidays first to see which state codes are available.',
            parameters: [
                { position: { key: 'jahr', value: '{{USER_PARAM}}', location: 'query' }, z: { primitive: 'string()', options: ['default("2026")', 'optional()'] } },
                { position: { key: 'nur_land', value: '{{USER_PARAM}}', location: 'query' }, z: { primitive: 'string()', options: ['min(2)', 'max(2)'] } }
            ],
            tests: [
                { _description: 'Get holidays for Bavaria 2026', nur_land: 'BY' },
                { _description: 'Get holidays for NRW 2026', nur_land: 'NW' }
            ],
            output: {
                mimeType: 'application/json',
                schema: {
                    type: 'object',
                    description: 'Public holidays for the requested state. Keys are German holiday names, values contain datum (ISO date YYYY-MM-DD) and hinweis (optional note, empty string if none). Not all holidays appear in every state.',
                    properties: {
                        Neujahrstag: { type: 'object', description: 'New Year\'s Day (January 1)', properties: { datum: { type: 'string', description: 'Holiday date in YYYY-MM-DD format' }, hinweis: { type: 'string', description: 'Optional note or caveat (empty string if none)' } } },
                        'Heilige Drei Könige': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } },
                        Karfreitag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } },
                        Ostermontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } },
                        'Tag der Arbeit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } },
                        'Christi Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } },
                        Pfingstmontag: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } },
                        Fronleichnam: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } },
                        'Augsburger Friedensfest': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } },
                        'Mariä Himmelfahrt': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } },
                        'Tag der Deutschen Einheit': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } },
                        Allerheiligen: { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } },
                        'Buß- und Bettag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } },
                        '1. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } },
                        '2. Weihnachtstag': { type: 'object', properties: { datum: { type: 'string' }, hinweis: { type: 'string' } } }
                    }
                }
            },
        }
    }
}


export const handlers = ( { sharedLists, libraries } ) => ( {
    getAllHolidays: {
        postRequest: async ( { response, struct, payload } ) => {
            const raw = struct?.data
            if( !raw || typeof raw !== 'object' ) { return { response }}

            const states = Object.entries( raw )
            .map( ( [ state, holidays ] ) => {
            const holidayList = Object.entries( holidays )
            .map( ( [ name, info ] ) => {
            const result = { name, date: info.datum, note: info.hinweis || null }

            return result
            } )

            return { state, holidayCount: holidayList.length, holidays: holidayList }
            } )

            response = {
            stateCount: states.length,
            states
            }

            return { response }
        }
    },
    getStateHolidays: {
        postRequest: async ( { response, struct, payload } ) => {
            const raw = struct?.data
            if( !raw || typeof raw !== 'object' ) { return { response }}

            const holidays = Object.entries( raw )
            .map( ( [ name, info ] ) => {
            const result = { name, date: info.datum, note: info.hinweis || null }

            return result
            } )

            response = {
            holidayCount: holidays.length,
            holidays
            }

            return { response }
        }
    }
} )
