// Migrated from v1.2.0 -> v2.0.0
// Category: simple

export const main = {
    namespace: 'profilejump',
    name: 'ProfileJump',
    description: 'Access LUKSO Universal Profile data via ProfileJump — token prices, trending profiles, token listings, and profile lookups by address.',
    version: '4.0.0',
    docs: ['https://profilejump.com'],
    tags: ['lukso', 'identity', 'profiles', 'cacheTtlDaily'],
    root: 'https://api.profilejump.com',
    headers: {
        Referer: 'https://profilejump.com/'
    },
    tools: {
        prices: {
            method: 'GET',
            path: '/api/prices',
            description: 'Fetch current token price data from ProfileJump for LUKSO Universal Profile ecosystem tokens and assets.',
            parameters: [],
            tests: [
                { _description: 'Fetch default prices' }
            ],
            output: {
                mimeType: 'application/json',
                schema: {
                    type: 'object',
                    properties: {
                        data: { type: 'object', properties: { lyxPrice: { type: 'string' }, lyxPriceChange: { type: 'string' }, totalValidatorsNumber: { type: 'number' }, totalValidatorsNumberChange: { type: 'number' }, totalLYXStaked: { type: 'number' }, totalLYXStakedChange: { type: 'number' }, lyxStakedValue: { type: 'string' }, lyxStakedValueChange: { type: 'string' }, currentProfilesLyxBalance: { type: 'string' }, totalProfilesLyxBalanceChange: { type: 'string' }, currentProfilesLyxValue: { type: 'number' }, profilesLyxValueChange: { type: 'string' }, currentProfilesTotalNumber: { type: 'string' }, profilesTotalNumberChange: { type: 'string' } } }
                    }
                }
            },
        },
        hotProfiles: {
            method: 'GET',
            path: '/api/profiles/hot-profiles',
            description: 'Fetch currently trending Universal Profiles ranked by recent activity. Use returned addresses in profileByAddress for full profile details.',
            parameters: [],
            tests: [
                { _description: 'Fetch trending profiles' }
            ],
            output: {
                mimeType: 'application/json',
                schema: {
                    type: 'array',
                    items: {
                        type: 'object',
                        properties: {
                            address: { type: 'string' }
                        }
                    }
                }
            },
        },
        tokensList: {
            method: 'GET',
            path: '/api/tokens-list?limit=100&offset=0',
            description: 'Fetch list of tokens with pagination via profilejump. Returns structured JSON response data.',
            parameters: [],
            tests: [
                { _description: 'Fetch tokens list' }
            ],
            output: {
                mimeType: 'application/json',
                schema: {
                    type: 'array',
                    items: {
                        type: 'object',
                        properties: {
                            address: { type: 'string' },
                            name: { type: 'string' },
                            symbol: { type: 'string' },
                            current_holders: { type: 'string' },
                            phantom_holders: { type: 'string' },
                            total_supply: { type: 'string' },
                            creators: { type: 'array', items: { type: 'string' } },
                            description: { type: 'string' },
                            tags: { type: 'array', items: { type: 'string' } },
                            links: { type: 'array', items: { type: 'object' } },
                            metadata_status: { type: 'string' },
                            metadata_error: { type: 'string', nullable: true },
                            selected_icon_image_url: { type: 'string' },
                            selected_icon_image_validation_status: { type: 'boolean' },
                            selected_icon_image_error: { type: 'string', nullable: true },
                            selected_image: { type: 'string' },
                            selected_image_validation_status: { type: 'boolean' },
                            selected_image_error: { type: 'string', nullable: true },
                            selected_background_image: { type: 'string' },
                            selected_background_image_validation_status: { type: 'boolean' },
                            selected_background_image_error: { type: 'string', nullable: true },
                            holders_24h: { type: 'string' },
                            holders_7d: { type: 'string' },
                            holders_1m: { type: 'string' },
                            volume_usd: { type: 'object', properties: { h24: { type: 'string' } } },
                            price_usd: { type: 'string' },
                            price_usd_1h_change: { type: 'string' },
                            price_usd_24h_change: { type: 'string' },
                            market_cap: { type: 'string' },
                            active_holders: { type: 'number' }
                        }
                    }
                }
            },
        },
        profilesList: {
            method: 'GET',
            path: '/api/profiles-list?limit=100&offset=0',
            description: 'Fetch list of profiles filtered by view via profilejump. Returns structured JSON response data.',
            parameters: [
                { position: { key: 'view', value: '{{USER_PARAM}}', location: 'query' }, z: { primitive: 'enum(social,wealth)', options: [] } }
            ],
            tests: [
                { _description: 'Fetch social view', view: 'social' },
                { _description: 'Fetch wealth view', view: 'wealth' }
            ],
            output: {
                mimeType: 'application/json',
                schema: {
                    type: 'array',
                    items: {
                        type: 'object',
                        properties: {
                            address_id: { type: 'number' },
                            address: { type: 'string' },
                            name: { type: 'string' },
                            tags: { type: 'array', items: { type: 'string' } },
                            links: { type: 'array', items: { type: 'object' } },
                            profile_image: { type: 'string' },
                            background_image: { type: 'string' },
                            current_balance: { type: 'string' },
                            twenty_four_hours: { type: 'string' },
                            twenty_four_hours_change: { type: 'string' },
                            seven_days: { type: 'string' },
                            seven_days_change: { type: 'string' },
                            one_month: { type: 'string' },
                            one_month_change: { type: 'string' },
                            current_following_count: { type: 'number' },
                            one_hour_following_count: { type: 'number' },
                            one_hour_following_count_change: { type: 'string' },
                            twenty_four_hours_following_count: { type: 'number' },
                            twenty_four_hours_following_count_change: { type: 'string' },
                            seven_days_following_count: { type: 'number' },
                            seven_days_following_count_change: { type: 'string' },
                            one_month_following_count: { type: 'number' },
                            one_month_following_count_change: { type: 'string' },
                            current_followers_count: { type: 'number' },
                            one_hour_followers_count: { type: 'number' },
                            one_hour_followers_count_change: { type: 'string' },
                            twenty_four_hours_followers_count: { type: 'number' },
                            twenty_four_hours_followers_count_change: { type: 'string' },
                            seven_days_followers_count: { type: 'number' },
                            seven_days_followers_count_change: { type: 'string' },
                            one_month_followers_count: { type: 'number' },
                            one_month_followers_count_change: { type: 'string' },
                            current_tokens_balance: { type: 'number' },
                            tokens_addresses: { type: 'string' },
                            current_nfts_balance: { type: 'number' }
                        }
                    }
                }
            },
        },
        profileByAddress: {
            method: 'GET',
            path: '/api/profiles/:address',
            description: 'Fetch full profile details by wallet address. Use addresses from hotProfiles or profilesList. Returns balance history, follower metrics, and token holdings.',
            parameters: [
                { position: { key: 'address', value: '{{USER_PARAM}}', location: 'insert' }, z: { primitive: 'string()', options: ['regex(^0x[a-fA-F0-9]{40}$)'] } }
            ],
            tests: [
                { _description: 'Valid address profile fetch', address: '0x02e2ae57Ed6058e41F19C402173939d99ecC05C3' }
            ],
            output: {
                mimeType: 'application/json',
                schema: {
                    type: 'object',
                    properties: {
                        address_id: { type: 'number' },
                        address: { type: 'string' },
                        name: { type: 'string' },
                        description: { type: 'string' },
                        tags: { type: 'array', items: { type: 'string' } },
                        links: { type: 'array', items: { type: 'object', properties: { url: { type: 'string' }, title: { type: 'string' } } } },
                        profile_image: { type: 'string' },
                        background_image: { type: 'string' },
                        current_balance: { type: 'string' },
                        twenty_four_hours: { type: 'string' },
                        twenty_four_hours_change: { type: 'string' },
                        seven_days: { type: 'string' },
                        seven_days_change: { type: 'string' },
                        one_month: { type: 'string' },
                        one_month_change: { type: 'string' },
                        two_months: { type: 'string' },
                        two_months_change: { type: 'string' },
                        three_months: { type: 'string' },
                        three_months_change: { type: 'string' },
                        four_months: { type: 'string' },
                        four_months_change: { type: 'string' },
                        five_months: { type: 'string' },
                        five_months_change: { type: 'string' },
                        six_months: { type: 'string' },
                        six_months_change: { type: 'string' },
                        seven_months: { type: 'string' },
                        seven_months_change: { type: 'string' },
                        eight_months: { type: 'string' },
                        eight_months_change: { type: 'string' },
                        nine_months: { type: 'string' },
                        nine_months_change: { type: 'string' },
                        ten_months: { type: 'string' },
                        ten_months_change: { type: 'string' },
                        eleven_months: { type: 'string' },
                        eleven_months_change: { type: 'string' },
                        twelve_months: { type: 'string' },
                        twelve_months_change: { type: 'string' },
                        current_following_count: { type: 'number' },
                        following_addresses: { type: 'string' },
                        one_hour_following_count: { type: 'number' },
                        one_hour_following_count_change: { type: 'string' },
                        twenty_four_hours_following_count: { type: 'number' },
                        twenty_four_hours_following_count_change: { type: 'string' },
                        seven_days_following_count: { type: 'number' },
                        seven_days_following_count_change: { type: 'string' },
                        one_month_following_count: { type: 'number' },
                        one_month_following_count_change: { type: 'string' },
                        two_months_following_count: { type: 'number' },
                        two_months_following_count_change: { type: 'string' },
                        three_months_following_count: { type: 'number' },
                        three_months_following_count_change: { type: 'string' },
                        four_months_following_count: { type: 'number' },
                        four_months_following_count_change: { type: 'string' },
                        five_months_following_count: { type: 'number' },
                        five_months_following_count_change: { type: 'string' },
                        six_months_following_count: { type: 'number' },
                        six_months_following_count_change: { type: 'string' },
                        seven_months_following_count: { type: 'number' },
                        seven_months_following_count_change: { type: 'string' },
                        eight_months_following_count: { type: 'number' },
                        eight_months_following_count_change: { type: 'string' },
                        nine_months_following_count: { type: 'number' },
                        nine_months_following_count_change: { type: 'string' },
                        ten_months_following_count: { type: 'number' },
                        ten_months_following_count_change: { type: 'string' },
                        eleven_months_following_count: { type: 'number' },
                        eleven_months_following_count_change: { type: 'string' },
                        twelve_months_following_count: { type: 'number' },
                        twelve_months_following_count_change: { type: 'string' },
                        current_followers_count: { type: 'number' },
                        followers_addresses: { type: 'string' },
                        one_hour_followers_count: { type: 'number' },
                        one_hour_followers_count_change: { type: 'string' },
                        twenty_four_hours_followers_count: { type: 'number' },
                        twenty_four_hours_followers_count_change: { type: 'string' },
                        seven_days_followers_count: { type: 'number' },
                        seven_days_followers_count_change: { type: 'string' },
                        one_month_followers_count: { type: 'number' },
                        one_month_followers_count_change: { type: 'string' },
                        two_months_followers_count: { type: 'number' },
                        two_months_followers_count_change: { type: 'string' },
                        three_months_followers_count: { type: 'number' },
                        three_months_followers_count_change: { type: 'string' },
                        four_months_followers_count: { type: 'number' },
                        four_months_followers_count_change: { type: 'string' },
                        five_months_followers_count: { type: 'number' },
                        five_months_followers_count_change: { type: 'string' },
                        six_months_followers_count: { type: 'number' },
                        six_months_followers_count_change: { type: 'string' },
                        seven_months_followers_count: { type: 'number' },
                        seven_months_followers_count_change: { type: 'string' },
                        eight_months_followers_count: { type: 'number' },
                        eight_months_followers_count_change: { type: 'string' },
                        nine_months_followers_count: { type: 'number' },
                        nine_months_followers_count_change: { type: 'string' },
                        ten_months_followers_count: { type: 'number' },
                        ten_months_followers_count_change: { type: 'string' },
                        eleven_months_followers_count: { type: 'number' },
                        eleven_months_followers_count_change: { type: 'string' },
                        twelve_months_followers_count: { type: 'number' },
                        twelve_months_followers_count_change: { type: 'string' },
                        tokens_addresses: { type: 'string' },
                        current_tokens_balance: { type: 'number' },
                        one_hour_tokens_balance: { type: 'number' },
                        one_hour_tokens_balance_change: { type: 'string' },
                        twenty_four_hours_tokens_balance: { type: 'number' },
                        twenty_four_hours_tokens_balance_change: { type: 'string' },
                        seven_days_tokens_balance: { type: 'number' },
                        seven_days_tokens_balance_change: { type: 'string' },
                        one_month_tokens_balance: { type: 'number' },
                        one_month_tokens_balance_change: { type: 'string' },
                        two_months_tokens_balance: { type: 'number' },
                        two_months_tokens_balance_change: { type: 'string' },
                        three_months_tokens_balance: { type: 'number' },
                        three_months_tokens_balance_change: { type: 'string' },
                        four_months_tokens_balance: { type: 'number' },
                        four_months_tokens_balance_change: { type: 'string' },
                        five_months_tokens_balance: { type: 'number' },
                        five_months_tokens_balance_change: { type: 'string' },
                        six_months_tokens_balance: { type: 'number' },
                        six_months_tokens_balance_change: { type: 'string' },
                        seven_months_tokens_balance: { type: 'number' },
                        seven_months_tokens_balance_change: { type: 'string' },
                        eight_months_tokens_balance: { type: 'number' },
                        eight_months_tokens_balance_change: { type: 'string' },
                        nine_months_tokens_balance: { type: 'number' },
                        nine_months_tokens_balance_change: { type: 'string' },
                        ten_months_tokens_balance: { type: 'number' },
                        ten_months_tokens_balance_change: { type: 'string' },
                        eleven_months_tokens_balance: { type: 'number' },
                        eleven_months_tokens_balance_change: { type: 'string' },
                        twelve_months_tokens_balance: { type: 'number' },
                        twelve_months_tokens_balance_change: { type: 'string' },
                        current_nfts_balance: { type: 'number' },
                        one_hour_nfts_balance: { type: 'number' },
                        one_hour_nfts_balance_change: { type: 'string' },
                        twenty_four_hours_nfts_balance: { type: 'number' },
                        twenty_four_hours_nfts_balance_change: { type: 'string' },
                        seven_days_nfts_balance: { type: 'number' },
                        seven_days_nfts_balance_change: { type: 'string' },
                        one_month_nfts_balance: { type: 'number' },
                        one_month_nfts_balance_change: { type: 'string' },
                        two_months_nfts_balance: { type: 'number' },
                        two_months_nfts_balance_change: { type: 'string' },
                        three_months_nfts_balance: { type: 'number' },
                        three_months_nfts_balance_change: { type: 'string' },
                        four_months_nfts_balance: { type: 'number' },
                        four_months_nfts_balance_change: { type: 'string' },
                        five_months_nfts_balance: { type: 'number' },
                        five_months_nfts_balance_change: { type: 'string' },
                        six_months_nfts_balance: { type: 'number' },
                        six_months_nfts_balance_change: { type: 'string' },
                        seven_months_nfts_balance: { type: 'number' },
                        seven_months_nfts_balance_change: { type: 'string' },
                        eight_months_nfts_balance: { type: 'number' },
                        eight_months_nfts_balance_change: { type: 'string' },
                        nine_months_nfts_balance: { type: 'number' },
                        nine_months_nfts_balance_change: { type: 'string' },
                        ten_months_nfts_balance: { type: 'number' },
                        ten_months_nfts_balance_change: { type: 'string' },
                        eleven_months_nfts_balance: { type: 'number' },
                        eleven_months_nfts_balance_change: { type: 'string' },
                        twelve_months_nfts_balance: { type: 'number' },
                        twelve_months_nfts_balance_change: { type: 'string' },
                        profile_metadata_status: { type: 'string' },
                        profile_metadata_error: { type: 'string', nullable: true },
                        selected_profile_image_validation: { type: 'boolean' },
                        selected_background_image_validation: { type: 'boolean' },
                        selected_profile_image_error: { type: 'string', nullable: true },
                        selected_background_image_error: { type: 'string', nullable: true },
                        lyx_price: { type: 'string' }
                    }
                }
            },
        }
    }
}
